### ISSUE TITLE
TPRParser not detecting bonds.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#222]
When loading with a .tpr as the topology bond information isn't taken from the tpr.

I've attached a simple system, just a box of flexible water.

The angles seem to be loaded fine, just not the bonds?  `gmxdump` tells me that the tpr has the bonds.

I've tried rolling back to the 0.8.1 release and bonds still aren't in _psf so I don't think we broke it recently with the class based topologies.

There's also not any testing for the topology loading in tpr files.

Original issue reported on code.google.com by `richardjgowers` on 9 Mar 2015 at 11:17

Attachments:
* [topol.tpr](https://storage.googleapis.com/google-code-attachments/mdanalysis/issue-222/comment-0/topol.tpr)
* [out.gro](https://storage.googleapis.com/google-code-attachments/mdanalysis/issue-222/comment-0/out.gro)

**Comment by jandom** [comment]
I've resolved this particular case but I'm in possession of a tpr that gives incorrect number of bonds for both the old and the new version of the code. Sticking to the divide and conquer approach, I think the resolution is worthy of a push (in case it's needed). 

A much more complex case which breaks, both the old and the new version.
https://drive.google.com/file/d/0BzI3NK6qw0lJZkN6ajJjZ0ZfdUk/view?usp=sharing
https://drive.google.com/file/d/0BzI3NK6qw0lJQmlIX2thS3BUa2M/view?usp=sharing

**Comment by richardjgowers** [comment]
I guess that's good and bad news?  I'm leaving this open till TPRParser is 100%

**Comment by jandom** [comment]
That's probably a good idea actually - apologies for being trigger happy
with closing ;)

**Comment by orbeckst** [comment]
This is the last official issue in the 0.10 milestone. Any chance that this gets fixed in the next few days for a 0.10.0 release or should we release 0.10.0 and add it as a fix in e.g. 0.10.1 (would you want to do that @seb-buch ?). 
Or leave it open and rather work on a complete overhaul with Tsjerk's code?

**Comment by richardjgowers** [comment]
I'm game for doing this, I'm just not privy to the secret Tsjerk code :)

**Comment by orbeckst** [comment]
Tsjerk is having a go at this.
I'm moving it to a later milestone and we'll have to live with this issue in 0.10.0.

**Comment by jbarnoud** [comment]
I am currently working working on this issue and on #352 but they are not fixed yet. Constraints are not read as bonds in the current state of the code; actually, very few interactions are assigned by the parser to bonds, angles, dihedrals, or impropers. I should have a fix for that by tomorrow.

So this issue, so as #352, should remain open for now. They can stay assigned to me, though.

**Comment by richardjgowers** [comment]
Ah sorry, I read the commit and assumed I'd just merged that.  Thanks for doing this one, it's an annoying issue.
