### ISSUE TITLE
Code formatting, style guide enforcement and static cheks

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2450]
I recently started using code formatting (with [black](https://black.readthedocs.io/en/stable/)), style guide enforcement (with [flake8](http://flake8.pycqa.org/en/latest/index.html#)) and static code checks (with [mypy](http://mypy-lang.org/)). I tried to apply them to MDAnalysis for fun and came across to many warnings.

**Describe the solution you'd like**

I think it would be great to format MDA with [black](https://black.readthedocs.io/en/stable/) (or other tools) and then use  [flake8](http://flake8.pycqa.org/en/latest/index.html#) and [mypy](http://mypy-lang.org/) (or other tools) to spot and fix possible problems.

**Describe alternatives you've considered**

There are other tools that can be considered: [pylint](https://pylint.readthedocs.io/en/latest/), [isort](https://pypi.org/project/isort/), [ypaf](https://github.com/google/yapf), ...

**Additional context**

Many errors come from `MDAnalysis/migration/`.

You can have a look at [this commit](https://github.com/RMeli/mdanalysis/commit/2369d53615d15509f07db2fabb085adf6edf57cf) to see the result of automatic code formatting with [black](https://black.readthedocs.io/en/stable/).

**Comment by richardjgowers** [comment]
We had (or have?) pylint on, but it sometimes throws annoying errors which stop a PR merging.

i think with something like black, we'd have to have every contributor follow the style, which would mean either a) instructions for everyone on how to apply it easily or b) some sort of CI system which fixes up the formatting on merging.  Both seem like they'd add ongoing effort for not much real gain?

**Comment by RMeli** [comment]
@richardjgowers I just wanted to spark the discussion but I agree the ratio benefits/effort might be small. However, #2409 and #2411 could be easily spotted by static checks. I also have found some indentation errors here and there that will make the code fail when executed.

Automatic code formatting (with black or other) is useful only if used with pylint or flake8, so that it removes most of the useless formatting errors. (It might reduce commit diffs if everyone uses it, but this is a very marginal benefit). However, it's really easy to install (`pip install black`) and apply (`black .`).

**Comment by jbarnoud** [comment]
I am all in favour of linters and static analyzers. I am considering adding type hints when we would have dropped python 2. I am less keen on formating tools, though: the way I format my code is often deliberate and, sometimes, going against the convention helps with readability or other things.

**Comment by RMeli** [comment]
I think adding type hints will be a great! 

I understand that automatic code formatting is not something every developer is willing to accept, but it would be the easiest way to remove most of the linting problems in one go at the beginning. I haven't tried `pylint`, but `flake8` gives very reasonable complaints (when used after automatic code formatting). 

Most of the tools can be configured in `setup.cfg` in order to reach a general consensus.

**Comment by tylerjereddy** [comment]
I'd suggest only applying the CI linting to the `diff` if we do this, rather than driving the full code base through a large amount of churn. SciPy is working on adopting something like this in: https://github.com/scipy/scipy/pull/11423

I'd be cautious about adopting type hints---maybe if/when they become widely adopted at the base of our dependency tree in NumPy/SciPy, etc.

**Comment by RMeli** [comment]
I like the idea of linting only the `diff`!  What is the drawback of type hints if they are not well adopted by the dependencies?

**Comment by tylerjereddy** [comment]
There may not be any major drawback, I just mean it could be sensible to wait to see what the rest of the ecosystem decides to do (if anything) about hinting in scientific code.

For example, NumPy has an experimental repo for type hinting with arrays: https://github.com/numpy/numpy-stubs

See also long-standing issue here: https://github.com/numpy/numpy/issues/7370

Perhaps it may have some influence on what we might want to do.

**Comment by tylerjereddy** [comment]
Note that SciPy has started accepting PRs that add type hints to source code, so maybe the time for doing this is not really so far away. May want to wait until we officially drop Python 2 support, as noted above.

**Comment by lilyminium** [comment]
+1 on being apprehensive about autoformatters. My main objection is what they do to commit history. It's useful to look at a line of code and see who committed it in which PR, so you can check out any discussion and know who to direct questions to.

CI linting the diffs seem like a great idea and would remove some of the PEP8 comments on reviews.

**Comment by IAlibay** [comment]
Just tagging this additional discussion thread [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mdnalysis-devel/sSQ00RNQSkk/P-C7BLbTCAAJ).

**Comment by lilyminium** [comment]
https://github.com/marketplace/pep-8-speaks may be of interest.

**Comment by orbeckst** [comment]
I installed pep8-speaks for all of MDA — if it’s too annoying we can deactivate it again or only enable it for specific repos. 

One can also configure it with a config file as described in https://github.com/OrkoHunter/pep8speaks#configuration

**Comment by RMeli** [comment]
> +1 on being apprehensive about autoformatters. My main objection is what they do to commit history. It's useful to look at a line of code and see who committed it in which PR, so you can check out any discussion and know who to direct questions to.

Thanks to @mikemhenry, I realised that it is possible to [ignore specific commits](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html) when using `git blame` and it seems that this is now [supported by GitHub](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) as well.

> I am less keen on formatting tools, though: the way I format my code is often deliberate and, sometimes, going against the convention helps with readability or other things.

For this situation, it is possible to [ignore blocks of code or single lines](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html?highlight=fmt%3A%20on#code-style) with `# fmt: on/off` and `# fmt: skip`.

**Comment by jandom** [comment]
hi there, just adding my two cents – prompted by @RMeli in https://github.com/MDAnalysis/UserGuide/pull/270#issuecomment-1644471797 – in my experience code formatters and static analysis tools (black, isort, flake8, mypy) are tremendously valuable. They make the codebase more readable, more maintainable, and lower the bar for entry for new contributors. 

These tools (in my experience) are the de-facto standard in the industry, and familiarity with them is valuable. Of course, such tools only solve a narrow problem, they don't solve some of the most important feature requests, tech debt or bugs. But they are typically a low hanging fruit with a positive net impact on the health of a codebase and dev velocity.

**Comment by marinegor** [comment]
Hi everyone, just adding another two cents here -- git has a feature that allows you to ignore certain commits in `git blame`: https://stackoverflow.com/questions/53502654/how-do-i-run-a-code-formatter-over-my-source-without-modifying-git-history

Sadly it requires a configuration beforehand (you must run `git config blame.ignoreRevsFile .git-blame-ignore-revs` to make it work), and also doesn't (yet) work on the github's web interface -- although it's on a public beta since 8.03.2023 (check [here](https://github.com/orgs/community/discussions/5033)), so I assume it'll be available for everyone relatively soon.

I imagine that messing up `git blame` was one of the arguments *against* using automatic formatting -- so just saying there's a workaround here.

**Comment by jbarnoud** [comment]
I have been on record as one of those (if not the one) that dislike auto-formatting. I had issues with fixes that were suboptimal readability-wise, portions of the code where the formatting was intentional, and reformatting the existing code base breaking `git blame`.

With time, I come to accept that the few places where the formatting is suboptimal are outweighed by the benefit of auto-formatting. We can have guards where the formatting is intentional (like this superb [periodic table](https://github.com/MDAnalysis/mdanalysis/blob/66a2b215760750cdf5e62725249c6971e3ac8b34/package/MDAnalysis/topology/tables.py#L379)). If we can ignore some commits for the blame, then all my objections are addressed.

There is just the question of how to handle pending pull requests that risk being riddled with merge conflicts.

**Comment by IAlibay** [comment]
> We can have guards where the formatting is intentional 

I'm still not an amazing fan of `black` (I am less wary now that that formatting style documentation has improved & there is a "future" section) but I also don't care that much as long as we are careful not to worsen readability / destroy intentional formatting.

> There is just the question of how to handle pending pull requests that risk being riddled with merge conflicts.

In my opinion, the best approach would be to cut up the process in chunks. That way we can also review the changes in a sane way rather than have a million+ line changes. We work on files that aren't currently in progress, and if we get blocked by a PR that isn't going anywhere then that gives us a good reason to close stale PRs (of which we have many).

**Comment by IAlibay** [comment]
I would however add here (for the @MDAnalysis/coredevs) that I would urge a discussion on priorities here. We have a lot of maintenance work to do, and many PRs that need a push (including all the type hinting ones and the guesser stuff).

I'm not saying don't do it, I am however saying let's consider the order in which we do things.

**Comment by marinegor** [comment]
Is it possible that you add a project-wide autoformatter settings, and then for all new PRs you ask people to a) run the formatter on the files they're changing b) add the respective commit to the `.git-blame-ignore-revs` file? Perhaps this might help reducing the number of merge conflicts, as well as delay the necessity to run it for all files at once.

**Comment by IAlibay** [comment]
> Is it possible that you add a project-wide autoformatter settings, and then for all new PRs you ask people to a) run the formatter on the files they're changing b) add the respective commit to the `.git-blame-ignore-revs` file? Perhaps this might help reducing the number of merge conflicts, as well as delay the necessity to run it for all files at once.

I don't think that'll work - you'll get conflicts with files where folks are touching the same file.

**Comment by marinegor** [comment]
>I don't think that'll work - you'll get conflicts with files where folks are touching the same file.

But if the settings are project-wide, their autoformatting (should) match unless they touched the same parts of the code?
I'm not sure though, never tried it.

**Comment by orbeckst** [comment]
EDIT: Sorry folks — I thought this question happened on Egor's PR, not on the **dedicated static code formatters issue** ...so this is exactly where discussion should happen... oops. So most of what I wrote doesn't apply really. I am just crossing out the embarrassing lines... except the bit that says if anyone wants to push for such a change they better be ready to be responsible for handling it.

-----

I think we can cut the discussion pretty short: We can consider autoformatters ~~but it ain't gonna happen in this PR as it's too big of a change. I am all for a productive discussion for how to move forward but can we please have it in a sensible place — either an issue or a thread on the developer list?~~


~~@marinegor apologies for stomping in here. From your perspective it's a sensible discussion to ask here as you're focused on your work and want to get it done efficiently.~~ From a project-wide perspective it's a discussion that has come up a few times. It looks as opinions are shifting so it's ok to have this discussion from time to time — nothing is set in stone — but in the context of the project it's a big, big undertaking and we have to weigh cost (=time/opportunity) vs benefit. ~~Let's do this in a dedicated place that won't distract from what your PR is about.~~ 

So can I ask that if anyone cares enough about the topic of autoformatters, ~~they start a discussion on the dev list (or open/re-open(?) an issue) and point all interested parties there... and~~ **then feel responsible for following up on the discussions**? Thanks.

**Comment by RMeli** [comment]
A real life example (discussed live with @orbeckst and @marinegor) of why I think automatically formatting the code base would be a QOL improvement, at least for some developers. This is just to illustrate why some people would really like this to happen, although I completely agree that there are more pressing issues that need attention and it might be a poor choice to saturate the narrow developer bandwidth we have with this kind of work.

--- 

If I open `bat.py` with my `neovim` configuration, I get the following:
![Screenshot from 2024-09-16 16-36-23](https://github.com/user-attachments/assets/2b379def-3572-4ca8-839d-12bc9504762c)

As you can see in the bottom status bar, the language server gives 67 errors (!) and 2 warnings. Most of the errors are clearly spurious and due to poor formatting, which is lingering in the code base. It is annoying to have so many errors show up, but the main issue is that the spurious errors can hide actual errors (and with too many errors, the language server even gives up at some point).

By typing `,lf` in "normal mode" I can perform automatic formatting, and I get the following:
![Screenshot from 2024-09-16 16-36-44](https://github.com/user-attachments/assets/3b106698-98c2-4bb8-9e3c-d984ea946dbc)

From 67 errors and 2 warnings, down to 8 errors with 3 key presses! =) Now I can actually focus on the errors that might be real. In the screenshot, it is still a spurious error, although my understanding is that the `if a not in b` construct is more Pythonic than `if not a in b`. Moreover, not having the language server scream at me at every other line, I can better focus on coding.

**Comment by marinegor** [comment]
Hi everyone, after discussion with Oliver, Rocco and (on discord) Irfan, here's what I'd suggest to do with the formatting.
There's some rationale and statistics at first, and then the proposed process for changes. Pinging @MDAnalysis/coredevs here, if I may.


# Rationale for introducing the formatter & linter

Long-term, introducing a code formatter + code linter combo (implemented both within `ruff` tool -- less dependencies!):
 
 - minimizes the time and effort spent on style discussions ~~like this one~~
 - lowers the "energy barrier" for PRs from newcomers who use formatters and linters (like me)
 - makes spotting potential bugs and annoying PEP8 violations easier via making linter suggestions more meaningful, and not purely style-related (see @RMeli message above)
 - ...also moves the spotting to pre-push stage
 - does not limit options for custom code formatting via a single `# fmt: skip` mark on statements or `# fmt: off <statement> # fmt: on` guards for bigger parts
 - there's a mechanism for ignoring purely formatting commits in both [git blame](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt) and [github](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)


However, introducing formatted code in one automatically formatted PR has a downside: there are many places where automatic formatting (previously, with `black`) decreases readability, and hence manual formatting suppression guards must be placed there by one of the core devs. Such PR is too big (374 changed files on current `develop` branch), so if any, this should be done with many small PRs, as suggested by @IAlibay. Even though it's still a big change, let's dive into how actually big it is.


# Stats

Some statistics about the changes (comparing `ruff format && ruff check --fix` commit vs current develop aka `319b6676a5`), is below.
I should also note that significant amount of changes is trivial -- e.g. newline added/removed, quites replaced to double quotes, etc. I could not (easily) get exact numbers on types of changes, but just eye-balling, I can say that it's a lot.


## Total number of changes

If we do `ruff format && ruff check --fix` (the first one is purely a formatter, second one is changes things like `if not foo in iterable` to `if foo not in interable` and removes unused imports), there are **48479 lines of code changed**:

```bash
marin@homepc:~/github/mdanalysis$ git diff develop --ignore-all-space --ignore-blank-lines --shortstat
 357 files changed, 29223 insertions(+), 19256 deletions(-)
```

This is around 15% of all lines edited, given that MDAnalysis (including tests) is **150k lines of python code**.


## Number of changes (in lines) per folder / module

This is amount of changes (in number of lines changed/removed/added), where a number of changes in an enclosing folder contains changes in subfolders as well. Namely, 60% of formatting changes are in `testsuite`, and only 40% in the main package (with a third of them being in `analysis`), or 20k lines in total.


```bash
marin@homepc:~/github/mdanalysis$ git diff develop --ignore-all-space --ignore-blank-lines --dirstat=lines,1,cumulative
   2.3% package/MDAnalysis/analysis/encore/
   2.4% package/MDAnalysis/analysis/hydrogenbonds/
   1.2% package/MDAnalysis/analysis/legacy/
  12.5% package/MDAnalysis/analysis/
   8.1% package/MDAnalysis/coordinates/
   6.4% package/MDAnalysis/core/
   2.8% package/MDAnalysis/lib/
   4.2% package/MDAnalysis/topology/
   1.0% package/MDAnalysis/visualization/
  37.8% package/MDAnalysis/
  38.9% package/
  14.1% testsuite/MDAnalysisTests/analysis/
   1.5% testsuite/MDAnalysisTests/converters/
  13.4% testsuite/MDAnalysisTests/coordinates/
  12.2% testsuite/MDAnalysisTests/core/
   1.0% testsuite/MDAnalysisTests/formats/
   6.2% testsuite/MDAnalysisTests/lib/
   4.0% testsuite/MDAnalysisTests/topology/
   2.5% testsuite/MDAnalysisTests/utils/
  59.5% testsuite/MDAnalysisTests/
  59.6% testsuite/
```

## Top-10 `package` files

Gigantic files that contribute to 30% of all changes in `package` (and only 19 files with more than 300 changed lines):

```bash
 package/MDAnalysis/analysis/nuclinfo.py            |  456 ++++---
 package/MDAnalysis/coordinates/PDB.py              |  463 ++++---
 package/MDAnalysis/analysis/encore/similarity.py   |  500 ++++----
 package/MDAnalysis/lib/distances.py                |  509 +++++---
 package/MDAnalysis/core/selection.py               |  572 ++++++---
 package/MDAnalysis/analysis/legacy/x3dna.py        |  619 +++++++--
 package/MDAnalysis/coordinates/H5MD.py             |  696 ++++++-----
 .../analysis/hydrogenbonds/wbridge_analysis.py     |  823 +++++++-----
 package/MDAnalysis/core/groups.py                  |  898 ++++++++------
 package/MDAnalysis/core/topologyattrs.py           |  904 ++++++++------
```

## Some manual inspection: `analysis` module

I've also looked through the files that were changed in the `analysis` module (that I'm familiar with), like 80% of them are either of those:
 
 - newlines added/removed here and there
 - single quotes to double quotes
 - spaces around operators
 - unused imports

A good thing that I've noticed, comparing to `black`, is that it doesn't enforce short lines, i.e. if you put a trailing comma in the list of arguments, it won't remove it for (it won't remove any symbols, basically):

```bash
marinegor@homepc$ ruff format asdf.py --diff
--- asdf.py
+++ asdf.py
@@ -1 +1,2 @@
-def func(x: int, y: int, z: int): return x+y+z
+def func(x: int, y: int, z: int):
+    return x + y + z

1 file would be reformatted
marinegor@homepc$ vi asdf.py 
marinegor@homepc$ ruff format asdf.py --diff
--- asdf.py
+++ asdf.py
@@ -1 +1,6 @@
-def func(x: int, y: int, z: int,): return x+y+z
+def func(
+    x: int,
+    y: int,
+    z: int,
+):
+    return x + y + z
```


# Proposed process for introducing changes

Following up on "many small PRs" idea by Irfan, I'd suggest the following process for adoption:

1. A pilot project: we team up with @RMeli doing formatting for a chosen small piece of codebase (I'd suggest `analysis` module, though open for discussion). I submit PRs like [this one](https://github.com/marinegor/mdanalysis/pull/2), where obvious changes (like the ones mentioned above) are done in the first commit, and others (for Rocco's review) are in the second, to save his time. We also update `.git-ignore-blame-revs` respecitvely.
2. I submit a PR for adding `ruff` github action, manually adding files that are being modified.

---

After the pilot:

3. The codebase gets split into chunks of code (say, 2-3 files not touched by current PRs, 500 LOC change max -- to be updated after the pilot), and PRs get submitted accordingly. Bonus point is that these PRs can be updated automatically any time a merge conflict appears.
4. The Contribution guide gets an explicit option (with a guide) to supplement a work-in-progress PR with a formatting PR -- basically, if the person working on the PR wants to do it with the help of linter/formatter, we provide them tools for that.

For the core developers reviewing the PRs, I guess it's fairly easy (from the typing point of view): if the formatting changes aren't ok, just click "suggest edits" and put two lines `# fmt: off` / `# fmt: on` around the edit, and move on.
For me doing the "easy commit / hard commit" part, it's also fairly easy -- I get to read the codebase, plus with tools like `git add -p` it's very fast.

**Comment by RMeli** [comment]
https://github.com/MDAnalysis/mdanalysis/pull/4810#pullrequestreview-2486257472 (from @tylerjereddy).
