### ISSUE TITLE
Catch when C extensions haven't been compiled on import

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2550]
There's a common error where users import MDAnalysis and the C extensions haven't been compiled & created.  This (currently) ends up manifesting as `no module called _cutil` as this is the first C extension submodule imported when MDAnalysis is imported.

I think putting a try/except around this first C-extension import and then issuing a better error message (possibly with some debug info) would be a nice feature

**Comment by YashAgrawal0** [comment]
@richardjgowers I'd like to work on this issue.

**Comment by shfrz** [comment]
@richardjgowers  would love to fix this issue, any clue where to start?

**Comment by richardjgowers** [comment]
This is an example of the error that people get when the C extensions haven't been compiled: https://groups.google.com/forum/#!topic/mdnalysis-discussion/ipwJKoEy6dk

**Comment by shfrz** [comment]
@richardjgowers  It seems the issue has been resolved!

**Comment by ss62171** [comment]
@richardjgowers is this issue open to work?

**Comment by richardjgowers** [comment]
Yep

**Comment by ss62171** [comment]
@richardjgowers _cutil extension is imported in file ``` util.py ```. Do i have to add try except block there? And any idea like how to replicate this error.

**Comment by siddharthjain1611** [comment]
I'm still facing this error while running `pytest --cov=MDAnalysis`.

**Comment by kpiyush04** [comment]
Hi! @richardjgowers 
Can you please elaborate on this issue.

**Comment by orbeckst** [comment]
Typically, this error occurs when a user is doing something like
```bash
cd mdanalysis/package
python -e 'import MDAnalysis; print(MDAnalysis.__version__)'
```
but did not build or install MDAnalysis.

I am not quite sure how we would test this (though maybe using [`mock`](https://docs.python.org/3/library/unittest.mock.html) might be a possibility — ??).

**Comment by ss62171** [comment]
_cutil is first C extension submodule that compiles, this generates a `.so` file on compiling. So basically if cython files are not compiled properly then this error occurs. Like if we delete this `.so` file then we can replicate this error since we won't be able to find this _cutil module.

**Comment by ss62171** [comment]
@orbeckst can I put a PR for this?

**Comment by orbeckst** [comment]
>  Like if we delete this .so file then we can replicate this error since we won't be able to find this _cutil module.

I don't think that we should consider crippling the installation during a test, i.e., there shouldn't be a test that deletes necessary files from the installed package. For a start, this breaks parallel tests but it might also break the package if you're running tests in one process and using the package in another (even if this might be rare).

While developing a test you could certainly do this to replicate the error.

**Comment by orbeckst** [comment]
I don't see a PR linked to this issue so please by all means, put up a PR @ss62171 !

**Comment by ss62171** [comment]
Should I add a try except block where this module is imported as @richardjgowers mentioned?

**Comment by orbeckst** [comment]
Try it and see if it is a good solution.
