### ISSUE TITLE
`Chemfiles`  change in float writing for 0.10.3 causing CI failures

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3798]
There seems to be an issue with `chemfiles` that is causing the full-deps builds to fail in #3127 and #3777 (likely others as well). I have re-triggered a few other jobs to check. 

It is worth noting that `chemfiles` released a new version on [pip](https://pypi.org/project/chemfiles/0.10.3/) yesterday (0.10.3) which could be the issue [see here for the tag](https://github.com/chemfiles/chemfiles.py/releases/tag/0.10.3). 

 I could reproduce the error (which seemed to be related to finding some shared library, at least on my computer) locally with a conda install of `chemfiles` but seemed to work OK for a pip install.

**Comment by Luthaf** [comment]
Chemfiles author here. I guess you are seeing the fact that the version of chemfiles on pip is already 0.10.3, but I did not had time to release 0.10.3 on conda yet. 

I looked through the linked issues, but I could not find the chemfiles CI error in #3777, and #3127 is not a PR (although chemfiles is not yet built for PPCLE64, I'll look into this). Could you point me to the CI run which failed?

EDIT: managed to build chemfiles for conda, this should be resolved once this PR (https://github.com/conda-forge/chemfiles-python-feedstock/pull/26) is merged.

**Comment by hmacdope** [comment]
Sorry typo on the issue number, #3797 was what I meant to type. :) here is (hopefully) a link to one of the failed CI runs for completeness https://github.com/MDAnalysis/mdanalysis/runs/8064088893?check_suite_focus=true

**Comment by IAlibay** [comment]
This is due to chemfiles-lib and chemfiles-python being out of synch (the latter having not been updated to 0.10.3 yet). 

@Luthaf this seems to be a rather common issue on release, is there anything we can do to help smooth out deployment on the chemfiles side of things?

**Comment by Luthaf** [comment]
> @Luthaf this seems to be a rather common issue on release, is there anything we can do to help smooth out deployment on the chemfiles side of things?

Yes, it is unfortunately common. I tried to fix this during the last release (have the python package load chemfiles from `libchemfiles.0.10.so` instead of `libchemfiles.0.10.2.so`), but realized just now my fix was broken. I have a fix for the fix (https://github.com/chemfiles/chemfiles.py/pull/43/commits/e5702be5a7d4c7b1843ac2c1c964652c2428bd56) which will come in the next release.

On my side I'll add more tests for the conda-style deployment (using libchemfiles not packaged together with the Python module). On your side, you could pin chemfiles to a specific version, and I can help to manually upgrade it whenever a new release is out. Hopefully this kind of issue will go away as I get closer to a 1.0 release.

**Comment by IAlibay** [comment]
> On your side, you could pin chemfiles to a specific version, and I can help to manually upgrade it whenever a new release is out. Hopefully this kind of issue will go away as I get closer to a 1.0 release.

This isn't an ideal solution so I'd prefer we not have to do this unless it's our only resort.

@Luthaf with a little bit more thought this seems to me to be a broken conda-forge recipe? Could you not either pin the chemfiles-lib version in the recipe to match the chemfiles-python version or at least do a `<= {{ version }}`? This would ensure that conda doesn't resolve mismatching dependencies.

**Comment by Luthaf** [comment]
So in theory chemfiles-python 0.10.2 should be able to run with chemfiles-lib 0.10.3 without a problem (the C API stayed the exact same). The issue comes from chemfiles-python, which is trying to load `libchemfiles.0.10.2.so` (only available in chemfiles-lib 0.10.2) where it should be loading `libchemfiles.0.10.so` (available in both 0.10.2 and 0.10.3).

Once 0.10.3 is fully released, I'll mark chemfiles-python 0.10.2 as broken/edit the dependency to `==0.10.2` in there.

**Comment by Luthaf** [comment]
Ok, chemfiles-python 0.10.3 is now on conda-forge, you should be able to restart the CI runs! Sorry for the inconvenience.

**Comment by IAlibay** [comment]
@Luthaf CI is no longer failing on a version clash, but it is failing on an assert: https://github.com/MDAnalysis/mdanalysis/runs/8072864136?check_suite_focus=true#step:7:293

Did something change with 0.10.3 which would likely cause this?

**Comment by richardjgowers** [comment]
Since chemfiles is optional, can we mark these as knownfailures so we can do the release? It's annoying to hold up the release on this.

**Comment by IAlibay** [comment]
Yeah I'm going to xfail the one test - it's a float writing issue anyways.

**Comment by IAlibay** [comment]
Ok I've re-named the issue to better match the current state of things.

It would be good to try to un-xfail the test after 2.3.0 gets released.
